<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = ['PEOPLE_PERSON_ID','PEOPLE_PERSON_NUMBER','PEOPLE_BADGE_NUMBER','PEOPLE_FIRST_NAME','PEOPLE_LAST_NAME','EMP_COMMON_FULL_NAME','PEOPLE_MANAGER_NAME','PEOPLE_EMAIL','PEOPLE_PHONE_NUMBER','EMP_COMMON_PRIMARY_ORG','EMP_COMMON_PRIMARY_JOB_TITLE','EMP_COMMON_PRIMARY_JOB_DESCRIPTION','PEOPLE_HIRE_DATE','PEOPLE_SENIORITY_DATE'];
}
